# Generated by Django 4.1.7 on 2023-03-07 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0003_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='magasin.fournisseur'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='adresse',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
