# Generated by Django 4.1.7 on 2023-03-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0005_commande_produitnc'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='Product',
            field=models.ManyToManyField(to='magasin.product'),
        ),
    ]
