# Generated by Django 4.1.7 on 2023-03-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0006_commande_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='Product',
        ),
        migrations.AddField(
            model_name='commande',
            name='produits',
            field=models.ManyToManyField(to='magasin.product'),
        ),
    ]
